doctrine_phpcr:
    session:
        backend:
            type: jackrabbit
            url: http://localhost:8080/server/
        workspace: default
        username: admin
        password: admin
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"