services:

    cms.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - ["/cms/content/pages"]
        tags:
            - { name: doctrine_phpcr.initializer }
