services:

    dreamhood_cms.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - ["/cms/content/pages", "/cms/routes"]
        tags:
            - { name: doctrine_phpcr.initializer }
