services:
    dreamhood_cms.admin.page:
          class: Dreamhood\CmsBundle\Admin\PageAdmin
          arguments:
              - ''
              - Dreamhood\CmsBundle\Document\Page
              - 'SonataAdminBundle:CRUD'
          tags:
              - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Site Content', label: 'Pages' }
          calls:
              - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]