parameters:
#    dreamhood_cms.example.class: Dreamhood\CmsBundle\Example

services:
#    dreamhood_cms.example:
#        class: %dreamhood_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
